
export const strings = {
    'app_name': "MediBank",
    'welcomemedilog': 'Welcome to MediLog',
    'signintoyouraccount': 'Sign in to your account',
    'signIn':'Sign In',
    'email': 'Email',
    'password':'Password',

    'mobile_number': 'Mobile Number',
    'requestOTP': 'Request OTP',
    'Donthaveanaccount': 'Don’t have an account?',
    'signUp': 'Sign Up',
    'vyaparMitra': 'Vyapar Mitra',
    'verifyOTP': 'Verify OTP',
    'otp': 'OTP',
    'notreceivedyourcode': 'Not received your OTP?',
    'resendCode': 'Resend OTP',
    'verify': 'Verify',
    'alert': 'Alert',
    'please': 'Please',
    'enter': 'Enter',
    'valid': 'Valid',
    'ok': 'Ok',
    'cancel': 'Cancel',
    'continue': 'Continue',
    'update': 'Update',
    'proceed': 'Proceed',
    'login': 'Login',
    'countery_code': '+91',
    'createAccount': 'Create account',
    'pleaseEnterAllTheDetails': 'Please enter all the details',
    'name': 'Name',
    'firmName': 'Firm Name',
    'state': 'State',
    'district': 'District',
    'villageCity': 'Village/City',
    'pincode': 'Pincode',
    'addressLineOne': 'Address Line 1',
    'addressLineTwo': 'Address Line 2',
    'save': 'Save',
    'version': 'Version',
    'profile': 'Profile',
    'logout': 'Logout',
    'myaccount': 'My Account',
    'address': 'Address',
    'settings': 'Settings',
    'faq': 'FAQ',
    'faqs': 'FAQ',
    'helpdesk': 'Help desk',
    'changePicture': 'Change Picture',
    'general': 'General',
    'address': 'Address',
    'firmInformation': 'Firm Information',
    'familyDetails': 'Family Details',
    'dateofBirth': 'Date of Birth',
    'storeName': 'Store Name',
    'addressOne': 'Address One',
    'taluk': 'Taluk',
    'alternativeNumber': 'Alternate Mobile Number',
    'gstNumber': 'GST Number',
    'panNumber': 'PAN Number',
    'maritalStatus': 'Marital Status',
    'marriageAnniversary': 'Marriage Anniversary',
    'spouseBirthDate': 'Spouse Birth Date',
    'city': 'City',

    'search': 'Search',
    'enrolment': 'Enrolment',
    'mobileApp': 'Mobile App',
    'pointsEarning': 'Points Earning',
    'redemption': 'Redemption',
    'howcanwehelp': 'How can we help',
    'didntfindtheanswer': 'Didn’t find the answer you were looking for? Contact our support center!',
    'Search topic or questions': 'Search topic or questions',
    'supportTickets': 'Support Tickets',
    'pluseComplaint': '+ Complaint',
    'complaint': 'Complaint',
    'customersupport': 'Customer Support',
    'selectCategory': 'Select Category',
    'selectSubCategory': 'Select Sub Category',
    'remarks': 'Remarks',
    'submit': 'Submit',
    'select': 'Select',
    'expertOnCall': 'Expert on Call',
    'helplineNum': '1800-572-7200',
    'selectAddress': 'Select Address',
    'usermyCurrentLocation': 'Use my current location',
    'addAddress': 'Add Address',
    'savedAddress': 'SAVED ADDRESSES',
    'bysigningupyouagreetoour': 'By signing up you agree to our',
    'termsConditions': 'Terms & Conditions',
    'and': 'and',
    'privacyPolicy': 'Privacy Policy',
    "create_new_token_message": "Creating a secure authentication code for you",
    "otp_generated_message_sms": "We have sent the OTP to your Phone as SMS",
    "otp_verify_message": "Please wait, we are verifying your OTP",
    "otp_verified_message": "Hurray! OTP verified",
    "otp_sent_successfully": "OTP Sent Successfully",
    "authentationSuccess": "Authentication Success",
    "please_wait_mpin_verifing": "Please wait, we are verifying your details",
    "please_wait_getting_data": "Please wait, while we are fetching your data...",
    "submitting_data": "We are submitting your data, please wait...",
    "data_submitted_successfully": "Data Submitted Successfully",
    'loading': 'Loading...',
    "getting_your_details": "Getting Your Details...",
    "pleasewaitloggingout": "Please wait logging out",
    "logout_successfully": "Logout Successfully",
    "no_data_available": "No Data Available",
    'success': 'Success',
    'code_expires_in': "OTP expires in:",
    'role': 'Role',
    "please_wait_creating_account": "Please wait, while we are creating your account...",
    "account_created_successfully": "Account Created Successfully",
    'something_went_wrong': 'Something Went Wrong. Please try again after sometime.',
    'goodMorning': 'Good Morning',
    'totalPoints': 'Total Points',
    'redeemedPoints': 'Redeemed Points',
    'ekyc': 'KYC',
    'imageUpload': 'Image Upload',
    'seedLicenseNumber': 'Seed License Number',
    'callNumber': '1800-572-3630',
    'tocontinuePleaseCheck': 'To continue please click on checkbox',
    'proprietorName': 'Proprietor Name',
    'tm': 'TM',
    'MDO': 'MDO',
    'skip': 'Skip',
    'landMark': 'Land mark',
    'couponsIssuesInvalidCoupons': 'Coupons issues - Invalid Coupons',
    'gotCouponsWhichareinvalid': 'Got coupons which are invalid',
    'status': 'Status',
    'documentUpload': 'Document Upload',
    'upload': 'Upload',
    "upload_document": "Upload Document",
    "upload_documents": "Upload Documents",
    'no_document_added': 'No Document is added',
    'youarealredayRegistered': 'You are already registered please login with registered mobile number',
    'village': 'Village',
    'tashilBlock': 'Tashil / Block',
    'helpCenter': 'Help Center',
    'products': 'Products',
    'promotions': 'Promotions',
    'camera': 'Camera',
    'gallery': 'Gallery',
    "camera_permission_ios": "NSL app requires Camera permission to capture and upload your images",
    "photo_permission_ios": "NSL app requires Photo Library permission to upload your images",
    "enable": "Enable",
    'getStarted': 'Get Started',
    'claim_points': 'Claim Points',
    'totalCumPoints': 'Total Cummulative Points',
    'please_make_qr_code_infocus': 'Please make sure QR code is in focus and clearly visible on your screen. Please scan B QR Code',
    'scan_more': 'Scan More',
    'done': 'Done',
    'congratulations': 'Congratulations',
    'coins_earned_success': 'You have earned 100 points on scanning off',
    'WelcometoVyaparMitra': 'Welcome to Vyapar Mitra',
    'scan_history': 'Scan History',
    'to_date': 'To Date',
    'from_Date': 'From Date',
    'view': 'View',
    'kharif': 'Kharif',
    'rabi': 'Rabi',
    'recomendedGeography': 'Recommended Geography :',
    'skuAvailable': 'SKUs available:',
    'pointswillbecreditedtoyouraccount': 'Points will be credited to your account',
    'select_season': 'Select Season',
    'season': 'Season',
    'credit': 'Credit',
    'debit': 'Debit',
    'imageAdded': 'Image Added',
    'points': 'Points',
    'productwisepointsdetails': 'Product wise points details',
    'coupon_id': 'Coupon Id',
    'transaction_id': 'Transaction Id',
    'transaction_date': 'Transaction Date',
    'transaction_time': 'Transaction Time',
    'credit_points': "Credit Points",
    'debit_points': 'Debit Points',
    'filters': 'Filters',
    'oldtoNew': 'Old to New',
    'newtoOld': 'New to Old',
    'scan': 'Scan',
    'redeem': 'Redeem',
    'redemHistory': 'Redemptions History',
    'verifryEkyc': 'Please complete kyc \n (or) \nGet approval from Territory manager Raise Request',
    'redemportalnotopen': 'Redemption portal is not open yet',
    'fileAttached': 'View Attached File',
    'comingSoon': 'Coming Soon',
    'type': 'Type',
    'help': 'Help',
    'memberType': 'Member Type',
    'notifications': 'Notifications',
    'theRequestHas': 'The request has been successfully sent to your territory manager',
    'total_cashback': 'Total Cash back earned till date',
    'selectDate': 'Select Date',
    'RequesthasBeenSubmit': 'Request has been submitted to territory manager, Name (mobileNumber)',
    'addconcernsbyyou': 'Addressed queries/Solutions provided',
    // 'addconcernsbyyou': 'Concerns raised by you / answers to your questions',
    'searching': 'Searching please wait...',
    'pleaseEnterText': 'Please Enter Some Text',
    'nosearchData': 'No Search Data is Find',
    'damagedCoupons': 'Damaged Coupons',
    'scanCouponLabel': 'Scan Coupon Label',
    'addCouponLabel': 'Add Coupon Label',
    'add_items': 'Add Item',
    'pleaseEnterScanCoupon': 'Please Enter Add Coupon Label',
    'selectCrop': 'Select Crop',
    'crop': 'Crop',
    'apply': 'Apply',
    'upload_gst_doc': "Upload GST Document",
    'upload_pan_doc': "Upload PAN Document",
    'upload_license_doc': 'Upload License Document',
    'brandName': 'Brand Name:',
    'productCode': 'Product Code:',
    'primaryPacking': 'Primary Packing',
    'bagSize': 'Bag Size',
    'pointsORBags': 'Points/Bag',
    'nuziveeduSeeds': 'Nuziveedu Seeds',
    'ekycSubmitted': 'Please wait untill the submitted kyc approved by TM',
    'basic_information': 'Basic Information',
    'theRequestHas': 'The request has been successfully sent to your territory manager',
    'imageAdded': 'Image Added',
    "redeem_successfully": "Redeem Successfully",
    "added_successfully": "Added to Cart Successfully",
    "please_wait": "Please wait...",
    "please_wait_redeem_adding": "Please wait, while we are adding to cart",
    "please_wait_redeem_delete": "Please wait, while we are deleting from cart",
    "deleted_successfully": "Deleted Successfully",
    'noenoughpoints': 'No enough points to redeem',
    'noenoughpointsaddCart': 'No enough points to add to cart',
    'yourcartisempty': 'Your cart is empty',
    //new
    //rewards
    'rewards': 'Rewards',
    'sku': 'SKU',
    'qty': 'Qty',
    'rewards_catalogue': 'Rewards Catalogue',
    'all': 'All',
    'products': 'Products',
    'vouchers': 'Vouchers',
    //cart
    'cart': 'Cart',
    'delete': 'Delete',
    //rewards
    'add_to_cart': 'Add to cart',
    'redeem': 'Redeem',
    'redemptions_history': 'Redemptions History',
    'products': 'Products',
    //notifications
    'notifications': 'Notifications',
    'no_internet_conneccted': 'No Internet available. plese try again after some time',
    'please_select_item': 'Please select any item',
    "searchByOrderId": "Search by order ID",
    "pleaseSelectFromDate": "Please select from date",
    "pleaseSelectToDate": "Please select to date",
    "voucherName": "Voucher Name",
    "transactionId": "Transaction Id",
    "totalItem": "Total Item",
    "totalPoints": "Total Points",
    "redeemedDate": "Redeemed date",
    "sno": 'S.No',
    'noofbagsScanned': 'Number of bags scanned',
    'back': 'Back',
    'couponCode': 'Coupon Code',
    'products': 'Products',
    'already_registered': 'You are already registered please login with registered mobile number.',
    'grand_total': 'Grand Total',
    'bonus_points': 'Bonus Points',
    'total_reward_points': 'Total Reward Points',
    'upload_seed_license_doc': "Upload Seed License Document",
    'no_internet_conneccted': 'No Internet available. Please try again after some time',
    'retailerInfo': 'Retailer Info',
    'complaint_raised_successfuly': 'Complaint Raised Successfully',
    'no_notifcations': 'No Notifications Available',
    'retailerInfo_updated_successfully': 'Retailer info updated successfully',
    'kyc_data_submitted_successfully': 'KYC data submitted successfully',
    'all': 'All',
    "profileUpdatedSuccessfully": "Profile updated successfully.",
    "approve": 'Approved',
    'bypass': 'byPass',
    'reject': 'Reject',
    'pending': 'Pending',
    'issue': 'Issue',
    'redeemedPoints': 'Redeemed Points',
    'rewards': 'Rewards',
    'eky_pending': 'Your submitted KYC data is under approval',
    'ekyc_approved': 'Your KYC has been approved',
    'delete': 'Delete',
    'zone': 'Zone',
    'selectZone': 'Select Zone',
    'selectRegion': 'Select Region',
    'selectTerritory': 'Select Territory',
    'selectHeadquarter': 'Select Headquarter',
    'year': 'Year',
    'selectYear': 'Select Year',
    'getDetails': 'Get Details',
    'retailerName': 'Retailer Name',
    'selectRetailerName': 'Select Retailer Name',
    'scanned_already': 'This coupon is already scanned',
    'scan_saved': 'The coupon data has been successfully saved. Reward points for redeemed coupons will be credited once the data synchronization is complete.',
    "kycApproval": "KYC Approval",
    "kycApprovalCap": "KYC Approval",
    "kycApprovalDetails": "KYC Approval Details",
    "retailerName": "Retailer Name",
    "requestedDate": "Requested Date",
    "status": "Status",
    "approveKYC": "Approve",
    "selectApproveReject": "Select Approve/Reject",
    "pleaseSelectKycToApprove": "Please select KYC to approve or reject",
    "invalid_coupons": "Invalid Coupons",
    "activeRetailers": "Active Retailers :",
    "are_you_sure_want_to_logout": 'Are you sure want to logout ?',
    "retailer": "Retailer",
    "distributor": "Distributor",
    'update_message': "New version is available! Please download it.",
    "kycApproval": "Kyc Approval",
    "designation": "Designation",
    "zone": "Zone",
    "region": "Region",
    "territory": "Territory",
    "headquarters": "Headquarters",
    'earned_points': 'Earned Points',
    'signUp_bonus': 'Signup Bonus',
    "kycApproval": "Kyc Approval",
    "designation": "Designation",
    "zone": "Zone",
    "region": "Region",
    "territory": "Territory",
    "headquarters": "Headquarters",
    "employeeId": "EmployeeId",
    "employeeName": "Employee Name",
    "gender": "Gender",
    "alternateMobileNumber": "Alternate Mobile No",
    "enterPanDetails": "Enter PAN Details",
    "request": "Request",
    "history": "History",
    'selectALl': 'Select All',
    'deSelectAll': 'Unselect All',
    'selectedCount': 'Selected Count :',
    "salesTeam": "R-E Mapping",
    "totalCashBackEarnedTillDate": "Total Cash back earned till date",
    'registeredRetailer': 'Registered Retailers',
    'retailerType': "Retailer Type",
    'selectRetailerType': "Select Retailer Type",
    'signUp_bonus_points': 'Signup Bonus Points',
    "selectGender": "Select Gender",
    "logged_in_other_device": 'This user is already logged in on another device, so you will be logged out.',
    'editOnly': 'Edit',
    'please_enter_min_four': 'Minimum four characters required for',
    'rejected': 'Rejected',
    'ekyc_rejected': 'Your KYC has been rejected',
    'editInfo': "Press and hold on the image to delete or upload it.",




    // MediLog Strings
    'fullName': 'Full Name',
    'emergencyContactNumber' : 'Emergency Contact Number',
    'cityTown' : 'City/Town',
    'bloodGroup' : 'Blood Group',
    'confirmPassword' : 'Confirm Password',
    'chooseLanguage' : 'Choose Language',
    'choosepreferredLanguage' : 'Choose your preferred language',
    'addPhoto' : 'Add Photo',
    'hospitalClinicName' : 'Hospital/Clinic Name',
    'doctorName' : 'Doctor Name',
    'procedure' : 'Procedure',
    'patientName' : 'Patient Name',

}  
